# Site settings
email: "dsc444@nyu.edu"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Pandora's box by Dan Castano
description: "Designer and code geek interested in the power of the fun. This is Daniel Castano from Colombia. This BLOG includes mental process and learning progress documentation. However, you are more than welcome participate as an active collaborator. All the experiments, insights, projects, solutions, coffees, materials, people, pizza, you will problably find in this space are part of the experience of ITP - Interactive telecommunication program (Master program), which is taught by NYU at Tisch School of arts.

This blog was done with Github pages + Jekyll + Thomas Vaeth template. Tools to share and promote opensource code and teamwork."
url: "trafalmejo.github.com"
twitter_username: 
default_img: "https://unsplash.it/?random"

# Profile settings
name: 
profile_img: "https://unsplash.it/?random"
profile: 
social:
  github: "https://github.com/trafalmejo"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
