# Site settings
email: jacob1818@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-92622016-1

# SEO settings
title: Jacob's .. blog(?)
description: Short collection of insights and thoughts. Feel free to tag along.
url: "http://jacobsalzberg.github.io/db"
twitter_username: jacobjsalzberg
default_img: "https://jacobsalzberg.github.io/db//static/profile_img.jpg"

# Profile settings
name: Jacob J. Salzberg
profile_img: "https://jacobsalzberg.github.io/db//static/profile_img.jpg"
profile: Jacob was born in Sao Paulo and feels really detached. Full time "Indie" Developer, former engineer. Welcome to his world. This blog is mostly used as a relief tool and as a progress tracker (personal and project related). Hop on!
social:
  github: http://github.com/jacobsalzberg
  steam: http://steamcommunity.com/id/jacobjames/
  facebook: http://www.facebook.com/jacob.salzberg
  linkedin: http://www.linkedin.com/in/jacobsalzberg
  twitter: https://twitter.com/jacobjsalzberg
  google-plus: https://plus.google.com/u/0/+JacobS1818
  

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
