# Site settings
email: dsc4@nyu.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Pandora's box by Dan Castano
description: Short collection of insights and thoughts.
url: ""
twitter_username: trafalmejo
default_img:

# Profile settings
name: Pandora's box by Dan Castano
profile_img: 
profile: Daniel Castano, colombian Designer and developer studying master program Interactive Telecommunication program (ITP) at Tisch School of Arts, NYU. This blog has documentation purposes. Feel free to contribute and five feedback. Be bold, be brave. Godspeed. 
social:
  github: http://github.com/trafalmejo
  facebook: http://www.facebook.com/dscastano
  

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
